'use strict';
// One short lesson per week; all lessons remain available for self-paced learning.
const aiLessons = [
 {title:'What is AI?',tag:'Rules & reasoning',text:'Artificial intelligence is a broad name for computer systems that do tasks such as recognizing patterns, making predictions, or planning. Some follow rules people write. Others learn patterns from examples. A simple rule is useful, but not every rule-based program is called AI.',nodes:['Person writes rules','Computer checks facts','Suggested action'],example:'A basketball helper could use a rule: if practice is tomorrow, remind me to pack my shoes. An expert system combines many rules to help solve a problem.',activity:'Draw a decision tree for packing your bag. Start with “Is there practice tomorrow?” Add a yes branch and a no branch.',question:'Which describes a rule-based helper?',choices:['It checks instructions a person wrote.','It must learn from thousands of photos.','It has feelings about the answer.'],answer:0,why:'People supply the rules. The computer applies them to the facts it is given.',word:'Algorithm',meaning:'A series of steps for doing a task.'},
 {title:'Learning from examples',tag:'Machine learning',text:'In machine learning, training adjusts a model using examples. Later, the trained model uses the patterns it learned on new inputs. Training examples and fresh test examples should be separate, so we can check whether it learned useful patterns rather than just remembered the practice set.',nodes:['Training examples','Adjust a model','Test with new examples'],example:'Labeled photos of basketballs and soccer balls can train a classifier. Classification chooses a category; regression predicts a number, such as a travel time. Unsupervised learning looks for patterns without supplied answer labels. Reinforcement learning uses rewards to learn actions over time.',activity:'Write six descriptions of balls and label each type. Invent two new descriptions to test your rule. What if every training basketball was orange, but your test basketball was blue?',question:'What makes a fair test of a trained model?',choices:['Only reuse its training examples.','Try examples it has not trained on.','Give it the answers before testing.'],answer:1,why:'New examples help reveal whether the model can use its patterns beyond the training set.',word:'Model',meaning:'A system whose settings help turn an input into a prediction or output.'},
 {title:'Small signals, one prediction',tag:'Neural networks',text:'A neural network combines numbers through connected units. Each connection has a weight that changes how much a signal matters. During training, a measure of error helps adjust those weights. Despite the name, it is not a tiny human brain.',nodes:['Inputs: shape & lines','Weighted connections','Ball-type prediction'],example:'Round shape alone does not tell a basketball from a soccer ball. A network can combine several clues. An activation function helps units represent more than simple straight-line relationships. Backpropagation calculates how weights contribute to error so training can adjust them.',activity:'Give two clues a score from 0 to 2: orange color and curved black lines. Add the scores to guess “basketball.” Now invent a case that fools your score. This is a tiny model demonstration, not a trained neural network.',question:'What changes when a neural network trains?',choices:['It grows human memories.','Its screen becomes larger.','Its connection weights are adjusted.'],answer:2,why:'Training adjusts numerical settings, including weights, to reduce errors on the training task.',word:'Weight',meaning:'A number controlling how much one signal influences another.'},
 {title:'Why “deep” learning?',tag:'Many layers',text:'Deep learning uses neural networks with many layers. Layers transform information into representations useful for a task. More layers alone do not guarantee a better answer: data, design, and testing matter too.',nodes:['Pixels in a photo','Layers combine visual clues','Prediction'],example:'In an image model, some features may capture edges, others textures or shapes. CNNs use local patterns in images. RNNs and LSTMs process sequences. Transformers use attention to relate parts of an input. These are different designs, not levels that every AI must climb.',activity:'Sketch a basketball using only short lines. Circle which lines form edges, then shapes, then the whole ball. Your sketch is an analogy for combining features, not a picture of a model’s actual thoughts.',question:'“Deep” mainly refers to…',choices:['Many layers in a neural network.','A computer having deep feelings.','Every answer being correct.'],answer:0,why:'Deep learning refers to multilayer neural networks, not human understanding or guaranteed accuracy.',word:'Feature',meaning:'A useful pattern or property in data, such as an edge or shape.'},
 {title:'How AI creates',tag:'Generative AI',text:'Generative AI produces new content using patterns learned during training. A language model generates text a token at a time using the context so far. A token can be a word, part of a word, or punctuation. Plausible text can still contain mistakes.',nodes:['Prompt + context','Model predicts next tokens','Generated draft'],example:'A language model might draft a team cheer. Many image generators use diffusion: they learn to remove noise step by step to form an image. These systems can create useful drafts, but their output is not proof of a fact.',activity:'Write “At practice, I brought my…” and invent three possible endings. Which fits best? Then write a two-line team cheer and check that it makes sense. You are simulating possible continuations, not training an AI.',question:'An AI gives a confident fact. What next?',choices:['Confidence proves it is true.','Check a reliable source.','Assume it is always false.'],answer:1,why:'Generated answers can sound convincing and still be wrong. Check important facts using a reliable source.',word:'Hallucination',meaning:'An AI output that presents invented or incorrect information as if it were true.'},
 {title:'Words, pictures & sound',tag:'Multimodal AI',text:'A multimodal system works with more than one kind of information, such as text and images. It might answer a question about a photo. That does not mean it understands every detail correctly or can see anything outside the input it receives.',nodes:['Picture + a question','Model combines input types','Answer to check'],example:'Given a picture of a court, a system might describe visible markings. It could misread a blurry scoreboard or miss a player behind another player. Multimodal describes kinds of input or output; it overlaps with other AI categories.',activity:'Describe a familiar court to someone without showing a picture. Then show a drawing. What became easier? What information, such as the game time, is still missing?',question:'Which task uses multiple kinds of input?',choices:['Sorting numbers only.','Completing a text sentence only.','Answering a typed question about a picture.'],answer:2,why:'The system uses both text and image information.',word:'Modality',meaning:'A kind of information, such as text, an image, audio, or video.'},
 {title:'When AI uses tools',tag:'AI agents',text:'An AI agent can work toward a goal by choosing steps and using tools, then checking the results. A tool might search a calendar or run a calculation. “Memory” often means saved information or retrieved notes, not human memory. People decide what tools and permissions it gets.',nodes:['Goal','Plan → use a tool','Check result → adjust'],example:'A trip helper could find options and draft a packing list. It should ask before actions such as booking or sharing information. Agents can make mistakes over several steps, so checks and limits matter. Not all agents use the same model design.',activity:'Pretend to be an agent planning a game day. Write a goal, three steps, and one check. Circle any step that needs a parent’s permission. Keep names, passwords, home addresses, and private schedules out of practice prompts.',question:'Before an agent buys tickets, it should…',choices:['Get approval from the responsible person.','Buy anything it predicts you like.','Skip checking dates.'],answer:0,why:'A purchase has real consequences. A person should confirm the choice and authorize it.',word:'Tool',meaning:'A capability a program can call, such as a calculator or calendar search.'},
 {title:'Design your own AI helper',tag:'Connect the ideas',text:'These ideas overlap. Machine learning is part of AI; neural networks are one machine-learning approach; deep learning uses multilayer networks. Generative systems create content, multimodal systems use multiple information types, and agents organize actions. They are not a strict ladder.',nodes:['Define a useful goal','Choose data + approach','Test, check & improve'],example:'Design a fictional basketball-bag helper: rules for required items, a photo classifier for equipment, and a generated checklist. It can suggest what is missing, while a person makes the final decision.',activity:'Draw your helper. Label its input, output, and any tools. Write two tests, one way it could fail, and one privacy rule. Use made-up information. Explain your design to a parent in two minutes.',question:'Which is the best final test plan?',choices:['Test only easy cases.','Include new and tricky cases, and check mistakes.','Trust it because it uses several AI methods.'],answer:1,why:'Useful testing includes unfamiliar and difficult examples. Combining methods does not remove the need to check results.',word:'Evaluation',meaning:'Checking how well a system works and where it fails.'}
];
let aiWeek=0;
function aiCompleted(){return Array.isArray(state.aiCompleted)?state.aiCompleted.filter(n=>Number.isInteger(n)&&n>=0&&n<aiLessons.length):[];}
function aiPage(){
 const done=aiCompleted();const suggested=aiLessons.findIndex((_,i)=>!done.includes(i));
 return intro('AI LAB','Big ideas. Small weekly steps.','Eight weeks to explore how AI works. Try one 10-minute lesson each week, or learn at your own pace.')+
 `<section class="panel ai-roadmap"><div class="eyebrow">YOUR LEARNING PATH</div><h2>${done.length} of ${aiLessons.length} weeks complete</h2><p class="note">All lessons are available now. Progress stays on this device. These activities work offline and do not send messages to an AI.</p><button class="primary" id="ai-continue">${suggested<0?'Revisit week 1':'Continue with week '+(suggested+1)}</button><div class="ai-weeks" aria-label="Choose a weekly lesson">${aiLessons.map((l,i)=>`<button class="small-button" data-ai-week="${i}" aria-pressed="${i===aiWeek}">Week ${i+1}${done.includes(i)?' ✓':''}<span>${escapeHTML(l.title)}</span></button>`).join('')}</div></section><div id="ai-lesson"></div>`;
}
function drawAILesson(){
 const l=aiLessons[aiWeek];
 document.querySelector('#ai-lesson').innerHTML=`<section class="panel ai-lesson"><div class="eyebrow">WEEK ${aiWeek+1} · ${escapeHTML(l.tag)}</div><h2 tabindex="-1" id="ai-title">${escapeHTML(l.title)}</h2><p>${escapeHTML(l.text)}</p><figure class="ai-diagram"><figcaption>A simple picture of the idea</figcaption><ol>${l.nodes.map(n=>`<li>${escapeHTML(n)}</li>`).join('')}</ol></figure><p>${escapeHTML(l.example)}</p><p class="ai-word"><strong>${escapeHTML(l.word)}</strong> — ${escapeHTML(l.meaning)}</p><h3>Try it yourself · 5 minutes</h3><p>${escapeHTML(l.activity)}</p><fieldset class="ai-check"><legend>Quick check: ${escapeHTML(l.question)}</legend>${l.choices.map((c,i)=>`<button class="small-button" data-ai-answer="${i}">${escapeHTML(c)}</button>`).join('')}</fieldset><p id="ai-feedback" role="status"></p><label class="check-row"><input id="ai-done" type="checkbox" ${aiCompleted().includes(aiWeek)?'checked':''}><span>I finished this week’s lesson and activity.</span></label>${aiWeek<aiLessons.length-1?'<button class="primary" id="ai-next">Explore next week →</button>':'<p class="note">This is the final week. Revisit any lesson and improve your helper design.</p>'}</section>`;
 document.querySelectorAll('[data-ai-answer]').forEach(b=>b.onclick=()=>{const right=Number(b.dataset.aiAnswer)===l.answer;document.querySelector('#ai-feedback').textContent=(right?'That’s right! ':'Try again. ')+l.why;});
 document.querySelector('#ai-done').onchange=e=>{const done=new Set(aiCompleted());if(e.target.checked)done.add(aiWeek);else done.delete(aiWeek);state.aiCompleted=[...done];save();const y=window.scrollY;main.innerHTML=aiPage();bindAI();window.scrollTo(0,y);document.querySelector('#ai-done').focus({preventScroll:true});};
 const next=document.querySelector('#ai-next');if(next)next.onclick=()=>openAIWeek(aiWeek+1);
}
function openAIWeek(n){aiWeek=n;main.innerHTML=aiPage();bindAI();document.querySelector('#ai-title').focus();}
function bindAI(){document.querySelectorAll('[data-ai-week]').forEach(b=>b.onclick=()=>openAIWeek(Number(b.dataset.aiWeek)));document.querySelector('#ai-continue').onclick=()=>{const n=aiLessons.findIndex((_,i)=>!aiCompleted().includes(i));openAIWeek(n<0?0:n);};drawAILesson();}
